### ISSUE TITLE
ValueError: Textures do not match the dimensions of Meshes.

### ISSUE THREAD

**Issue by SJingjia** [jinlinyi/SparsePlanes#6]
Hi,
Thanks for your great job.
After running "python ./tools/inference_sparse_plane.py --config-file ./tools/demo/config.yaml --input ./tools/demo/teaser --output ./debug",  I met an error as follows, do you know what caused it and how to solve it？
Traceback (most recent call last):
  File "./tools/inference_sparse_plane.py", line 766, in <module>
    main()
  File "./tools/inference_sparse_plane.py", line 762, in main
    inference_pair(output_dir, model, dis_opt, con_opt, im0, im1)
  File "./tools/inference_sparse_plane.py", line 727, in inference_pair
    webvis=True,
  File "./tools/inference_sparse_plane.py", line 627, in save_pair_objects
    cam_meshes = get_camera_meshes(cam_list)
  File "/home/jia/workspace/plane_resc_210617/SparsePlanes/sparsePlane/sparseplane/utils/mesh_utils.py", line 378, in get_camera_meshes
    meshes = Meshes(verts=verts_list, faces=faces_list, textures=tex)
  File "/home/jia/anaconda3/envs/sparseplane/lib/python3.7/site-packages/pytorch3d/structures/meshes.py", line 436, in __init__
    raise ValueError(msg)
ValueError: Textures do not match the dimensions of Meshes.
![Screenshot from 2021-09-08 14-11-52](https://user-images.githubusercontent.com/28842290/132459117-6d306cb9-a49c-4443-96d3-b8e5f54316de.png)

**Comment by jinlinyi** [comment]
Hi, 

What is the pytorch3d version you are using?

**Comment by zhirui-gao** [comment]
@jinlinyi 
Hi,I've had the same problem.My pytorch3d version is 0.6.0.

**Comment by JasonQSY** [comment]
@zhirui-gao Can you try pytorch3d 0.4? Initially we used 0.2.5 I think https://github.com/jinlinyi/SparsePlanes/blob/main/requirements.txt#L3

Pytorch3d does have some changes in 0.5 and 0.6 which are not compatible with previous version. I haven't tested them yet.
